import avatarPersonnel from './assets/avatar-personnel.svg'
export const initialTree = 
{
    id: 1,
  person: {
    id: 1,
    avatar: null,
    department: 'none',
    name: 'Miquel Pineda-INIT',
    title: 'CEO',
    totalReports: 1,
  },
  hasChild: true,
  hasParent: true,
  managerId: 0,
  children: [{
    id: 36,
    person: {
      id: 36,
      avatar: avatarPersonnel,
      department: '',
      name: 'Reba Strickland',
      title: 'Engineering Manager',
      totalReports: 4,
    },
    hasChild: true,
    hasParent: true,
    // children: [],
  },
  {
    id: 32,
    person: {
      id: 32,
      avatar: avatarPersonnel,
      department: '',
      name: 'Brittany Murillo',
      title: 'Engineering Manager',
      totalReports: 0,
    },
    hasChild: true,
    hasParent: true,
    children: [{
      id: 56,
      person: {
        id: 56,
        avatar: avatarPersonnel,
        department: '',
        name: 'Suzette Rhodes',
        title: 'Engineering Manager',
        totalReports: 2,
        link: '',
      },
      hasChild: true,
      hasParent: true,
      // children: [],
    },
    {
      id: 66,
      person: {
        id: 66,
        avatar: avatarPersonnel,
        department: '',
        name: 'Janie Nash',
        title: 'Engineering Manager',
        totalReports: 0,
      },
      hasChild: true,
      hasParent: true,
    },
    {
      id: 76,
      person: {
        id: 76,
        avatar: avatarPersonnel,
        department: '',
        name: 'Jarvis Mitchell',
        title: 'Software Engineer',
        totalReports: 0,
      },
      hasChild: true,
      hasParent: true,
    },
    {
      id: 60,
      person: {
        id: 60,
        avatar: avatarPersonnel,
        department: '',
        name: 'Winford Wu',
        title: 'Software Engineer II',
        totalReports: 0,
      },
      hasChild: false,
      hasParent: true,
      children: [],
    },
    {
      id: 690,
      person: {
        id: 690,
        avatar: avatarPersonnel,
        department: '',
        name: 'Erasmo Pollard',
        title: 'Software Architect',
        totalReports: 0,
      },
      hasChild: false,
      hasParent: true,
      children: [],
    },
    {
      id: 790,
      person: {
        id: 60,
        avatar: avatarPersonnel,
        department: '',
        name: 'Carol Marquez',
        title: 'Senior Software Engineer',
        totalReports: 0,
      },
      hasChild: false,
      hasParent: true,
      children: [],
    }],
  },
  {
    id: 25,
    person: {
      id: 25,
      avatar: avatarPersonnel,
      department: '',
      name: 'Gustavo Prince',
      title: 'Engineering Manager',
      totalReports: 3,
    },
    hasChild: true,
    hasParent: true,
    children: [],
  },
  {
    id: 945,
    person: {
      id: 945,
      avatar: avatarPersonnel,
      department: '',
      name: 'Freddie Acosta',
      title: 'Engineering Manager',
      totalReports: 2,
    },
    hasChild: true,
    hasParent: true,
    children: [],
  }],
}